package at.ac.fhcampuswien;

/**
 * Represents one job listing on the DesignerJobs platform.
 *
 * This class is used as a data model between the frontend and the backend.
 * When the frontend sends JSON data to the backend, Spring converts that JSON
 * into a Job object automatically.
 */
public class Job {

    /**
     * Unique identifier of the job.
     * This value is generated by the backend in JobController.
     * The frontend does not need to send this field.
     */
    public String id;

    /**
     * Identifier of the client who posted the job.
     * Later this can be connected to the login/session system.
     * For the first version we can use a temporary value such as "client-1".
     */
    public String clientId;

    /**
     * Name of the company or client who posts the job.
     * This comes from the "Company / client name" field in post-a-job.html.
     */
    public String companyName;

    /**
     * Contact email address for the job listing.
     * This comes from the "Contact email" field in post-a-job.html.
     */
    public String contactEmail;

    /**
     * Title of the job listing.
     * Example: "Brand Identity Designer".
     */
    public String title;

    /**
     * Detailed project description.
     * Example: required deliverables, project goal, style, or expected result.
     */
    public String description;

    /**
     * General design category.
     * Examples: Web Design, Graphic Design, UI/UX Design, Interior Design.
     */
    public String category;

    /**
     * More specific design type.
     * Examples: logo, branding, ui/ux, web, illustration, motion.
     * For now this can have the same value as category if the form has no extra field.
     */
    public String designType;

    /**
     * Location information for the job.
     * In the current frontend form this can be remote, onsite, or hybrid.
     */
    public String location;

    /**
     * Budget range selected by the client.
     * In the current frontend form this is €, €€, or €€€.
     */
    public String budget;

    /**
     * Work mode of the job.
     * Examples: remote, on site, hybrid.
     * In the current frontend form this can be the same value as location.
     */
    public String workMode;

    /**
     * Optional project deadline.
     * The frontend sends this as a date string.
     * Example format: 2026-06-15.
     */
    public String deadline;

    /**
     * Optional tags for search and filtering.
     * Example: "logo, branding, identity".
     * For the first version this can stay empty.
     */
    public String tags;

    /**
     * Creation timestamp of the job listing.
     * This value is generated by the backend in JobController.
     * The frontend does not need to send this field.
     */
    public String createdAt;
}