package at.ac.fhcampuswien.job;

/**
 * Represents one job listing on the DesignerJobs platform.
 * Spring uses this class to convert JSON data from the frontend into a Java object.
 */
public class Job {

    public String id;           // Unique job ID, generated by the backend

    public String clientId;     // ID of the client who posted the job, later connected to login/session

    public String title;        // Job title, for example "Brand Identity Designer"

    public String description;  // Detailed project description entered by the client

    public String category;     // General design category, for example Web Design or Graphic Design

    public String designType;   // More specific design type, for example logo, branding, UI/UX or motion

    public String location;     // Location information, currently remote, onsite or hybrid

    public String budget;       // Budget range selected in the form, for example €, €€ or €€€

    public String workMode;     // Work mode, currently the same value as location

    public String deadline;     // Optional deadline as a date string, for example 2026-06-15

    public String tags;         // Optional tags for search and filtering, for example "logo, branding"

    public String createdAt;    // Creation timestamp, generated by the backend

    public int viewCount;       // Creation viewCount, generated by the backend
}